apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-cleaner-service-account
  namespace: services-promotions-develop
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-cleaner-role
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - get
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-cleaner-role-binding
subjects:
- kind: ServiceAccount
  name: deployment-cleaner-service-account
  namespace: services-promotions-develop
roleRef:
  kind: Role
  name: deployment-cleaner-role
  apiGroup: ""
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deployment-cleaner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      template:
        spec:
          serviceAccountName: deployment-cleaner-service-account
          containers:
          - name: deployment-cleaner
            image: bitnami/kubectl
            command:
              - bash
            args:
              - "-xc"
              - |
                kubectl -n services-promotions-develop get deployments
          restartPolicy: OnFailure